export enum InfrastructureType {
    SolarEnergyPlant = 'SolarEnergyPlant',
    EolicEnergyPlant = 'EolicEnergyPlant',
    GreenHydrogenPlant = 'GreenHydrogenPlant',
    BESS = 'BESS',
    Highway = 'Highway',
    HydroelectricEnergyPlant = 'HydroelectricEnergyPlant',
    SeaPort = 'SeaPort',
    Airport = 'Airport',
    Bridge = 'Bridge',
    Toll = 'Toll',
    RailwayNetwork = 'RailwayNetwork',
    ExportFacility = 'ExportFacility',
    ConnectorNetworks = 'ConnectorNetworks',
    OleoDuct = 'OleoDuct',
    ProcessingAndStoragePlant = 'ProcessingAndStoragePlant',
    TelecommunicationTower = 'TelecommunicationTower',
    DataCenter = 'DataCenter',
    OpticalFiber = 'OpticalFiber',
    Hospital = 'Hospital',
    School = 'School',
    PublicFacility = 'PublicFacility',
    AgricultureLand = 'AgricultureLand',
    AgricultureCompany = 'AgricultureCompany'
}