export enum ProjectStatus {
    Cancelled = 'Cancelled',
    Rejected = 'Rejected',
    RejectedAfterDueDiligence = 'RejectedAfterDueDiligence',
    PendingFirstContract = 'PendingFirstContract',
    PendingToApprove = 'PendingToApprove',
    PendingClosed = 'PendingClosed',
    PendingResources = 'PendingResources',
    Expired = 'Expired',
    Approved = 'Approved',
    Closed = 'Closed',
    AgreementClosed = 'AgreementClosed',
    TechnicalScoringAssets10 = 'TechnicalScoringAssets10',
    TechnicalReview = 'TechnicalReview',
    UnderContractWithOwner = 'UnderContractWithOwner',
    FirstFundingIncome = 'FirstFundingIncome',
    DueDiligence = 'DueDiligence',
    ContractWithCapital = 'ContractWithCapital',
    FundingAgreement = 'FundingAgreement',
    Escrow = 'Escrow',
    PermittingAndStructuring = 'PermittingAndStructuring',
    PermitsApproved = 'PermitsApproved',
    FinalClosing = 'FinalClosing',
    NotEconomicallyViable = 'NotEconomicallyViable'
}